version: '3'

services:

  collabora:
    build: ./collabora
    container_name: collabora
    restart: always
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      domain: "${NEXTCLOUD_HOST}"
      username: "${COLLABORA_USER}"
      password: "${COLLABORA_PASSWORD}"

  collabora-nginx:
    build: ./collabora-proxy
    restart: always
    container_name: collabora-proxy
    environment:
      VIRTUAL_HOST: "${COLLABORA_HOST}"
      LETSENCRYPT_HOST: "${COLLABORA_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    depends_on:
      - collabora
    networks:
      - proxy-tier
      - default

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - nextcloud.env

  redis:
    container_name: redis
    image: redis
    restart: always

  nextcloud:
    build: ./nextcloud
    restart: always
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/mnt/nextcloud
    env_file:
      - nextcloud.env
    depends_on:
      - db
      - redis

  nextcloud-proxy:
    build: ./nextcloud-proxy
    restart: always
    container_name: nextcloud-proxy
    volumes:
      - nextcloud:/var/www/html:ro
      - /mnt/nextcloud:/mnt/nextcloud
    environment:
      VIRTUAL_HOST: "${NEXTCLOUD_HOST}"
      LETSENCRYPT_HOST: "${NEXTCLOUD_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    depends_on:
      - nextcloud
    networks:
      - proxy-tier
      - default

  cron:
    build: ./nextcloud
    container_name: cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM

        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done

        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      CERT_NAME: "${CERT_NAME}"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
      ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"
    depends_on:
      - proxy

#  s3sync:
#    image: vladgh/s3sync
#    container_name: s3sync
#    volumes:
#      - /mnt/nextcloud:/data:ro
#    env_file:
#      - s3sync.env
#    environment:
#      SYNCDIR: "/data"
#    command: "cron"

volumes:
  db:
  nextcloud:
  conf.d:
  vhost.d:
  html:

networks:
  proxy-tier:
